# Pre-commit configuration for V3 workflow enforcement
# This ensures no commits can introduce legacy format regression

repos:
  - repo: local
    hooks:
      - id: v3-workflow-enforcement
        name: V3 Workflow Enforcement
        entry: python tests/test_v3_enforcement_runner.py
        language: system
        always_run: true
        pass_filenames: false
        stages: [commit, push]
        verbose: true

      - id: no-legacy-imports
        name: Check for Legacy Component Imports
        entry: bash
        args: ['-c', 'if grep -r "from.*file_processor import\|from.*gemini_service import" src/ --exclude-dir=deprecated; then echo "❌ Legacy component imports detected!"; exit 1; else echo "✅ No legacy imports found"; fi']
        language: system
        always_run: true
        pass_filenames: false

      - id: no-legacy-field-usage
        name: Check for Legacy Field Usage
        entry: bash
        args: ['-c', 'if grep -r "\"Donor Name\"\|\"Gift Amount\"\|qbCustomerStatus" src/ --exclude-dir=deprecated --exclude="*.md" --exclude="test_*"; then echo "❌ Legacy field usage detected!"; exit 1; else echo "✅ No legacy field usage found"; fi']
        language: system
        always_run: true
        pass_filenames: false

      - id: v3-component-presence
        name: Verify V3 Components Present
        entry: bash
        args: ['-c', 'files=("src/utils/enhanced_file_processor_v3_second_pass.py" "src/utils/gemini_adapter_v3.py" "src/utils/payment_combiner_v2.py"); for file in "${files[@]}"; do if [[ ! -f "$file" ]]; then echo "❌ Missing V3 component: $file"; exit 1; fi; done; echo "✅ All V3 components present"']
        language: system
        always_run: true
        pass_filenames: false
